import localFont from "next/font/local";
import "./globals.css";
import Header from "./Components/Layouts/Header";
import { AppProvider } from "./Components/AppContext";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Scoop Haven",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="max-w-4xl mx-auto p-4">
          <AppProvider>
            <Toaster />
            <Header />
            {children}
            <footer className="text-center text-gray-500 border-t p-8 mt-16">
              &copy; 2024 All rights reserved.
            </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
